services:
  api_host: "sol-oasis.physik.hu-berlin.de"
  api_base_path: "/nomad-oasis"
  upload_limit: 1000

oasis:
  is_oasis: true
  uses_central_user_management: true

north:
  jupyterhub_crypt_key: "978bfb2e13a8448a253c629d8dd84ff89587f30e635b753153960930cad9d36d"
  tools:
    options:
      jupyter:
        image: ghcr.io/exciting/sol-oasis/jupyter:main

meta:
  deployment: "oasis"
  deployment_url: "https://sol-oasis.physik.hu-berlin.de/nomad-oasis/api"
  maintainer_email: "kuban@physik.hu-berlin.de"

logstash:
  enable: false

mongo:
  db_name: nomad_oasis_v1

elastic:
  entries_index: nomad_oasis_entries_v1
  materials_index: nomad_oasis_materials_v1

celery:
  timeout: 3600

process:
  max_upload_size: 2040109465600 #255 Gb
